<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=big5">
<title>江湖抽獎</title></HEAD>
<body oncontextmenu=self.event.returnValue=false bgcolor="#000000" text="#ffffff" background="../linjianww/0064.jpg">
<%Session("choujiang")=true%>
<p align="center"><b><font color="#000000">想碰運氣請先進入聊天室！</font></b></p>
<p align="center"><A HREF="chou.asp"><font color="#0000FF">開始抽獎</font></A></p>
<p align="center"><font color="#000000">注：每次抽獎時間為1分鐘即60秒，抽完後100秒不領獎，</font></p>
<p align="center"><font color="#000000">系統就會自動取消你的領獎機會，機會難得，切勿錯過！</font></p>
</font></p>
</BODY>
</HTML>