<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=big5">
<title>江湖釣魚</title></HEAD>
<body oncontextmenu=self.event.returnValue=false bgcolor="#000000" text="#ffffff" background="../linjianww/0064.jpg">
<%Session("diaoyu")=true%>
<p align="center"><b><font color="#000000">請先進入聊天室後才進行釣魚！</font></b></p>
<p align="center"><A HREF="diao.asp"><font color="#0000FF">開始釣魚</font></A></p>
<p align="center"><font color="#000000">注：每次釣魚時間為半分鐘即30秒，上鉤後10秒不</font></p>
<p align="center"><font color="#000000">拉杆，魚就會溜走，成功的機率是10%，大家看見河裡有</font></p>
<p align="center"><font color="#000000">動靜了就用鼠標點動的地方，就有機會釣到魚，每1分鐘<br>
</font></p>
<p align="center"><font color="#000000">可以進行釣魚一次，如果魚跑了只有等下一次了。</font><font color="red">
</font></p>
</BODY>
</HTML>